//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maintenance.Application.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maintenance.Application.Helpers.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an Error Occurred Please Contact System Administrator.
        /// </summary>
        internal static string anErrorOccurredPleaseContactSystemAdministrator {
            get {
                return ResourceManager.GetString("anErrorOccurredPleaseContactSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code Not Correct.
        /// </summary>
        internal static string codeNotCorrect {
            get {
                return ResourceManager.GetString("codeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile Verficiation Success.
        /// </summary>
        internal static string mobileVerficiationSuccess {
            get {
                return ResourceManager.GetString("mobileVerficiationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile verification code.
        /// </summary>
        internal static string Mobileverificationcode {
            get {
                return ResourceManager.GetString("Mobileverificationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalNumberFoundBefore.
        /// </summary>
        internal static string NationalNumberFoundBefore {
            get {
                return ResourceManager.GetString("NationalNumberFoundBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Number Not Found.
        /// </summary>
        internal static string NationalNumberNotFound {
            get {
                return ResourceManager.GetString("NationalNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord Not Correct.
        /// </summary>
        internal static string PassWordNotCorrect {
            get {
                return ResourceManager.GetString("PassWordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberFoundBefore.
        /// </summary>
        internal static string PhoneNumberFoundBefore {
            get {
                return ResourceManager.GetString("PhoneNumberFoundBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProplemSendCode.
        /// </summary>
        internal static string ProplemSendCode {
            get {
                return ResourceManager.GetString("ProplemSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Not Found.
        /// </summary>
        internal static string RoomNotFound {
            get {
                return ResourceManager.GetString("RoomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user Are Deleted.
        /// </summary>
        internal static string userAreDeleted {
            get {
                return ResourceManager.GetString("userAreDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user Logged In Successfully.
        /// </summary>
        internal static string userLoggedInSuccessfully {
            get {
                return ResourceManager.GetString("userLoggedInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
